# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.runs/synth_1/design_2_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.cache/wt [current_project]
set_property parent.project_path C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar_pack.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar_axi_rd_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar_axi_wr_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar_base.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar_wrap_pack.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/crossbar_wrap.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/axi_full2lite_converter_pack.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/axi_full2lite_rd_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/axi_full2lite_wr_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/axi_full2lite_converter.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/boot_pack_zynq.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/boot_pack_zynq_sim.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/main_pack_opcodes.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/bram.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/uart_pack.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/uart_axi_rd_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/uart_axi_wr_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/uart_core.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/uart_fifo.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/uart.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/mlite_pack.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/alu.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/bus_mux.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/cpu_pack.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/cache_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/control.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/cpu_axi_rd_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/cpu_axi_wr_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/mem_cntrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/mem_ctrl.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/mlite_cpu.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/mult.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/pc_next.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/pipeline.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/ppadder.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/prefix_adder.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/reg_bank.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/mlite/shifter.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/rtl/platform/cpu.vhd
  C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/hdl/design_2_wrapper.vhd
}
add_files C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_5/bd_0c5c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_6/bd_0c5c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_7/bd_0c5c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_8/bd_0c5c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_9/bd_0c5c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_10/bd_0c5c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_11/bd_0c5c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_xadc_wiz_0_0/design_2_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_xadc_wiz_0_0/design_2_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.gen/sources_1/bd/design_2/design_2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/ssaba/Downloads/pdp_final/PDP2023_mult/PDP2023_mult/PDP/fpga/zynq_fpga/zynq_fpga.srcs/utils_1/imports/synth_1/design_2_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_2_wrapper -part xc7z020clg400-1 -directive FewerCarryChains -keep_equivalent_registers -resource_sharing off -no_lc
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
